version: '3.8'
services:
  python_env:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - variables.env
    depends_on:
      - "database"
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - variables.env