version: '3.8'
services:
  python_env:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/code
    depends_on:
      - "database"
  database:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
